- hosts: localhost
  gather_facts: no
  connection: local
  vars_prompt:

    - name: apiKey
      prompt: What is your Porkbun API Key (not secret key)?
      private: yes

    - name: secretKey
      prompt: What is your Porkbun Secret Key?
      private: yes

    - name: domain
      prompt: What is the domain name this change will be applied to?
      private: no

    - name: subdomain
      prompt: What is the subdomain this change will be applied to?
      private: no

    - name: localDir
      prompt: What location should we pull new changes at? (relative paths are safe)
      private: no

    - name: startCmd
      prompt: What command should be run to start the process?
      private: no
  
  tasks:
  - name: Include Secrets File
    include_vars:
      file: secrets.yml

  - name: Populate API Key
    replace:
      path: porkbun-DDNS/config.js
      regexp: 'pbAPIKey'
      replace: "{{ apiKey }}"

  - name: Populate Secret Key 
    replace:
      path: porkbun-DDNS/config.js
      regexp: 'pbSecKey'
      replace: "{{ secretKey }}"

  - name: Populate Domain
    replace:
      path: porkbun-DDNS/config.js
      regexp: 'domainName'
      replace: "{{ domain }}"

  - name: Populate Subdomain 
    replace:
      path: porkbun-DDNS/config.js
      regexp: 'subdomainName'
      replace: "{{ subdomain }}"

  - name: Populate Secret Key 
    replace:
      path: GithubCD/config.js
      regexp: 'localGitDir'
      replace: "{{ localDir }}"

  - name: Populate Secret Key 
    replace:
      path: GithubCD/config.js
      regexp: 'startCMD'
      replace: "{{ startCmd }}"


  